application: mlb_pitch_tracker
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /logo\.png
  static_files: img/logo.png
  upload: img/logo.png
- url: /static/css
  static_dir: css
- url: /static/js
  static_dir: js
- url: /static/img
  static_dir: img
- url: /.*
  script: /src/main.py

builtins:
- appstats: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"