coverage:
  precision: 2
  round: down
  range: 50...100

  status:
    project: false
    patch: 
      enabled: true
      target: 70%
    changes: false

  comment:
    layout: "header, diff"
    behavior: default
